config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  get 'login' => 'sessions#create', as: 'new_login'
  post 'login' => 'sessions#new', as: 'login'
  delete 'logout' => 'sessions#destroy', as: 'logout'
  post '/adds/:id' => 'adds#create'
  resources :users
  resources :songs
  resources :adds

end

app/models/add.rb
class Add < ActiveRecord::Base
  belongs_to :user
  belongs_to :song
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :user
  has_many :adds
  has_many :users, through: :likes
  validates :title, :artist, presence: true
  validates :title, :artist, length: { minimum: 2 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :songs
  has_many :adds
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true, format:{with: EMAIL_REGEX}
  before_save :downcase_fields

  def full_name
    "#{self.first_name.capitalize} #{self.last_name.capitalize}"
  end
  

  def downcase_fields
    self.email.downcase!
  end

end

app/controllers/adds_controller.rb
class AddsController < ApplicationController

  def index
    
  end


  
  def create
    add = Add.create(user_id: current_user.id, song_id: params[:id])
    redirect_to :back
    # if(student.valid? == false)
    # redirect_to "/dojo/#{params[:dojo_id]}/students/new", alert: student.errors.full_messages
    # end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :require_login
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session.key? 'user_id'
  end

  def require_login
    return redirect_to :root unless session.key? 'user_id'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
    @user = User.find_by(email: params[:email])
    errors = []
    if @user
      if @user.authenticate(params[:password])
        session[:user_id] = @user.id
        return redirect_to "/users/new"
      else
        errors << 'Invalid password' # errors << is the same as errors.push
      end

    else
      errors << 'No account with that email exists. Please register first.'
    end
    redirect_to :back, alert: errors
  end

  def destroy
    session.delete :user_id if session.key? 'user_id'
    redirect_to '/users'
  end

  def create
    users = User.find_by(email: params[:email])
    
    if users && users.authenticate(params[:password])
      session[:id] = users.id
      render "/users"
      else 
          flash[:alert] = users.errors.full_messages
          redirect_to "/users"          
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    # @products = Product.all
    @songs = Song.all

    # @songs = Song.where.not(user_id:current_user).where(buyer_id:0)
    # @products = Product.where.not(buyer_id == current_user)
  end

  # def count
  #   @count = Song.find_by(id: params["id"]).update(:count => count + 1)
  # end

  def show
    @song = Song.find(params[:id])
    @songshow = Add.select(:user_id, :song_id).distinct.where(song_id: params[:id]).where.not(user_id: current_user.id)
  end


  # def update
  #   Product.find_by(id: params["id"]).update(buyer_id:current_user.id, date:DateTime.now)
  #   redirect_to :back
  # end
  
  def create
    song = Song.create(title: params[:title], artist: params[:artist], user_id: current_user.id)
    if song.valid?
      return redirect_to "/songs"
    end
    redirect_to :back, alert: song.errors.full_messages
  end


  # def destroy
  #   Product.find(params[:id]).destroy
  #   redirect_to :back
  # end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    redirect_to '/songs'
  end

  def show
    @user = User.find(params[:id])
    @songs = Add.where(user_id: params[:id])
    # @song = Song.where(user_id: params[:id])
  end


  def create
    if new_user.valid?
      session[:user_id] = new_user.id
      return redirect_to '/songs'
    end
    redirect_to :back, alert: new_user.errors.full_messages
  end


  private
    helper_method def user
      @user ||= User.find_by(id: params[:id])
    end

    helper_method def new_user
      @new_user ||= User.create(user_params)
    end

    def user_params
      params.require(:user).permit(:first_name,:last_name,:email,:password)
    end

end

app/helpers/adds_helper.rb
module AddsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Playlist1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/songs/index.html.erb
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">

</head>

<body>
  <div class='container col-6'>
    <a class="btn btn-primary btn-sm mr-2" href="<%= logout_path %>" role="button" data-method="delete">Logout</a>


    <p>Hello
      <%= current_user.full_name.capitalize %>
    </p>

    <div>

      <table class="table table-striped table-sm">
        <p class="text-center">All songs</p>
        <thead>
          <tr>
            <th scope="col">Artist</th>
            <th scope="col">Title</th>
            <th scope="col">Number of times song has been added</th>
            <th scope="col">Add to Playlist</th>
          </tr>
        </thead>
        <tbody>
          <% if @songs %>
            <% @songs.each do |song| %>
              <tr>
                <td>
                  <%= song.artist %>
                </td>
                <td>
                  <a href="/songs/<%= song.id %>">
                    <%= song.title %>
                  </a>
                </td>
                <td>
                  <%= Add.where(song_id: song.id).count %>
                </td>

                <td>
                  <form action="/adds/<%= song.id %>" method="post">
                    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                    <input class="btn btn-primary btn-sm mr-2" type="submit" value="Add">
                  </form>
                </td>
                <% end %>
                  <% end %>
        </tbody>
      </table>
    </div>

    <% if flash[:alert] %>
      <% flash[:alert].each do |error| %>
        <p class="text-danger" class "font-weight-bold">
          <%= error %>
        </p>
        <% end %>
          <% end %>
            <div class="row">
              <div class="col-6">
                <p>Add a Song:</p>
                <form action="/songs" method="POST">
                  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                  <div class="form-group">
                    <input type="text" name="title" class="form-control" placeholder="Title">
                  </div>
                  <div class="form-group">
                    <input type="text" name="artist" class="form-control" placeholder="Artist">
                  </div>
                  <div class="form-group">
                    <button type="submit" name='submit' class="btn btn-outline-primary btn-lg btn-block">Add Song</button>
                  </div>
                </form>
              </div>
            </div>



  </div>
  <!--close container-->

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script>
</body>

</html>

app/views/songs/show.html.erb
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">

</head>

<body>
  <div class='container col-6'>
    <a class="btn btn-primary btn-sm mr-2" href="<%= logout_path %>" role="button" data-method="delete">Logout</a>
    <a class="btn btn-primary btn-sm" href="<%= songs_path %>" role="button">Dashboard</a>

    


    </table>
    <p>Other who have added
      <%= @song.artist %> -
        <%= @song.title%>
    </p>

    <div>

      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Number of times song has been added</th>
          </tr>
        </thead>
        <tbody>
          <% if @songshow %>
            <% @songshow.each do |song| %>
              <tr>
                <td>
                  <a href="/users/<%= song.user.id %>"> <%= song.user.full_name %></a>
                </td>
                <td>
                  <%= Add.where(song_id: song.song_id, user_id: song.user_id).count %>
                </td>
                
                <% end %>
                  <% end %>
        </tbody>
      </table>
  



  </div>
  <!--close container-->

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script>
</body>

</html>

app/views/users/index.html.erb
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">


  <title>Login/Registration</title>

  <body>
    <div class="container col-6">
      <% if flash[:alert] %>
        <% flash[:alert].each do |error| %>
          <p class="text-danger" class "font-weight-bold">
            <%= error %>
          </p>
          <% end %>
            <% end %>
              <div class="row">
                <div class="col-6">
                  <h1>Login</h1>
                  <form action="<%= login_path %>" method="POST">
                    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                    <div class="form-group">
                      <input type="email" name="email" class="form-control" placeholder="Email Address">
                    </div>
                    <div class="form-group">
                      <input type="password" name="password" class="form-control" placeholder="Password">
                    </div>
                    <div class="form-group">
                      <button type="submit" name='submit' class="btn btn-outline-primary btn-lg btn-block">Log In</button>
                    </div>
                  </form>
                </div>

                <div class="col-6">
                  <h1>Register</h1>
                  <form action="/users" method="POST">
                    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                    <div class="form-group">
                      <input type="text" name="user[first_name]" class="form-control" placeholder="First Name">
                    </div>
                    <div class="form-group">
                      <input type="text" name="user[last_name]" class="form-control" placeholder="Last Name">
                    </div>
                    <div class="form-group">
                      <input type="email" name="user[email]" class="form-control" placeholder="Email">
                    </div>
                    <div class="form-group">
                      <input type="password" name="user[password]" class="form-control" placeholder="Password">
                    </div>
                    <div class="form-group">
                      <button type="submit" name="submit" class="btn btn-outline-primary btn-lg btn-block">Register</button>
                    </div>
                  </form>
                </div>
              </div>
    </div>

app/views/users/show.html.erb
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">

</head>

<body>
  <div class='container col-6'>
    <a class="btn btn-primary btn-sm mr-2" href="<%= logout_path %>" role="button" data-method="delete">Logout</a>
    <a class="btn btn-primary btn-sm" href="<%= songs_path %>" role="button">Dashboard</a>




    </table>
    <p>
        
    </p>

    <div>

      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th scope="col">Artist</th>
            <th scope="col">Title</th>
            <th scope="col">Times Added</th>
          </tr>
        </thead>
        <tbody>
          <% if @songs %>
            <% @songs.each do |song| %>
              <tr>
                <td>
                    <%= song.song.artist %>
                </td>
                <td>
                    <%= song.song.title %>
                </td>
                <td>
                <%=Add.where(song_id: song.song.id).count%>
                </td>

                <% end %>
                  <% end %>
        </tbody>
      </table>




    </div>
    <!--close container-->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
      crossorigin="anonymous"></script>
</body>

</html>